import 金疮药_特大 from "./金疮药(特大).mjs";
import 魔法药_特大 from "./魔法药(特大).mjs";
import 集中宝玉 from "./集中宝玉.mjs";
import 回避宝玉 from "./回避宝玉.mjs";
import 复活符 from "./复活符.mjs";
import 牛肉饺 from "./牛肉饺.mjs";
import 黑线 from "./黑线.mjs";
import 骨头 from "./骨头.mjs";
import 大骨头 from "./大骨头.mjs";
import 大骨汤 from "./大骨汤.mjs";
import 骨斩刀 from "./骨斩刀.mjs";
import 大骨饺 from "./大骨饺.mjs";
import 锤子 from "./锤子.mjs";
import 白骨头巾 from "./白骨头巾.mjs";
import 白骨衣_女 from "./白骨衣(女).mjs";
import 白骨衣_男 from "./白骨衣(男).mjs";
import 勇猛宝玉 from "./勇猛宝玉.mjs";
import 勇猛神珠 from "./勇猛神珠.mjs";
import 虫血手镯 from "./虫血手镯.mjs";
import 虫血项链 from "./虫血项链.mjs";
import 虫血戒指 from "./虫血戒指.mjs";
import 鸡汤 from "./鸡汤.mjs";
import 鸡肉饺 from "./鸡肉饺.mjs";
import 觉醒宝玉 from "./觉醒宝玉.mjs";
import 饺子 from "./饺子.mjs";
import 强化宝玉 from "./强化宝玉.mjs";
import 蛋汤 from "./蛋汤.mjs";
import 蛋饺 from "./蛋饺.mjs";
import 忍耐宝玉 from "./忍耐宝玉.mjs";
import 制魔宝玉 from "./制魔宝玉.mjs";
import 鱼饵 from "./鱼饵.mjs";
import 酷寒宝玉 from "./酷寒宝玉.mjs";
import 灰色药粉 from "./灰色药粉.mjs";
import 花草茶 from "./花草茶.mjs";
import 魔性宝玉 from "./魔性宝玉.mjs";
import 魔性神珠 from "./魔性神珠.mjs";
import 肉汤 from "./肉汤.mjs";
import 强化软玉腰带 from "./强化软玉腰带.mjs";
import 软玉腰带 from "./软玉腰带.mjs";
import 强化软玉轮 from "./强化软玉轮.mjs";
import 软玉轮 from "./软玉轮.mjs";
import 强化软玉项链 from "./强化软玉项链.mjs";
import 软玉项链 from "./软玉项链.mjs";
import 强化软玉环 from "./强化软玉环.mjs";
import 软玉环 from "./软玉环.mjs";
import 强化软玉鞋 from "./强化软玉鞋.mjs";
import 软玉鞋 from "./软玉鞋.mjs";
import 大火把 from "./大火把.mjs";
import 中毒宝玉 from "./中毒宝玉.mjs";
import 守护宝玉 from "./中毒宝玉.mjs";
import 强化红玉腰带 from "./强化红玉腰带.mjs";
import 红玉腰带 from "./红玉腰带.mjs";
import 强化红玉鞋 from "./强化红玉鞋.mjs";
import 红玉鞋 from "./红玉鞋.mjs";
import 强化红玉轮 from "./强化红玉轮.mjs";
import 红玉轮 from "./红玉轮.mjs";
import 强化红玉项链 from "./强化红玉项链.mjs";
import 红玉项链 from "./红玉项链.mjs";
import 强化红玉环 from "./强化红玉环.mjs";
import 红玉环 from "./红玉环.mjs";

export default function Init(context: CS.Daboluo.Mir2.MirScripts.ServerInitializationScriptContext) {
    context.RecipeDefinitions.Add(金疮药_特大);
    context.RecipeDefinitions.Add(魔法药_特大);
    context.RecipeDefinitions.Add(集中宝玉);
    context.RecipeDefinitions.Add(回避宝玉);
    context.RecipeDefinitions.Add(复活符);
    context.RecipeDefinitions.Add(牛肉饺);
    context.RecipeDefinitions.Add(黑线);
    context.RecipeDefinitions.Add(骨头);
    context.RecipeDefinitions.Add(大骨头);
    context.RecipeDefinitions.Add(大骨汤);
    context.RecipeDefinitions.Add(骨斩刀);
    context.RecipeDefinitions.Add(大骨饺);
    context.RecipeDefinitions.Add(锤子);
    context.RecipeDefinitions.Add(白骨头巾);
    context.RecipeDefinitions.Add(白骨衣_女);
    context.RecipeDefinitions.Add(白骨衣_男);
    context.RecipeDefinitions.Add(勇猛宝玉);
    context.RecipeDefinitions.Add(勇猛神珠);
    context.RecipeDefinitions.Add(虫血手镯);
    context.RecipeDefinitions.Add(虫血项链);
    context.RecipeDefinitions.Add(虫血戒指);
    context.RecipeDefinitions.Add(鸡汤);
    context.RecipeDefinitions.Add(鸡肉饺);
    context.RecipeDefinitions.Add(觉醒宝玉);
    context.RecipeDefinitions.Add(饺子);
    context.RecipeDefinitions.Add(强化宝玉);
    context.RecipeDefinitions.Add(蛋汤);
    context.RecipeDefinitions.Add(蛋饺);
    context.RecipeDefinitions.Add(忍耐宝玉);
    context.RecipeDefinitions.Add(制魔宝玉);
    context.RecipeDefinitions.Add(鱼饵);
    context.RecipeDefinitions.Add(酷寒宝玉);
    context.RecipeDefinitions.Add(灰色药粉);
    context.RecipeDefinitions.Add(花草茶);
    context.RecipeDefinitions.Add(魔性宝玉);
    context.RecipeDefinitions.Add(魔性神珠);
    context.RecipeDefinitions.Add(肉汤);
    context.RecipeDefinitions.Add(强化软玉腰带);
    context.RecipeDefinitions.Add(软玉腰带);
    context.RecipeDefinitions.Add(强化软玉轮);
    context.RecipeDefinitions.Add(软玉轮);
    context.RecipeDefinitions.Add(强化软玉项链);
    context.RecipeDefinitions.Add(软玉项链);
    context.RecipeDefinitions.Add(强化软玉环);
    context.RecipeDefinitions.Add(软玉环);
    context.RecipeDefinitions.Add(强化软玉鞋);
    context.RecipeDefinitions.Add(软玉鞋);
    context.RecipeDefinitions.Add(大火把);
    context.RecipeDefinitions.Add(中毒宝玉);
    context.RecipeDefinitions.Add(守护宝玉);
    context.RecipeDefinitions.Add(强化红玉腰带);
    context.RecipeDefinitions.Add(红玉腰带);
    context.RecipeDefinitions.Add(强化红玉鞋);
    context.RecipeDefinitions.Add(红玉鞋);
    context.RecipeDefinitions.Add(强化红玉轮);
    context.RecipeDefinitions.Add(红玉轮);
    context.RecipeDefinitions.Add(强化红玉项链);
    context.RecipeDefinitions.Add(红玉项链);
    context.RecipeDefinitions.Add(强化红玉环);
    context.RecipeDefinitions.Add(红玉环);
}