import 卫士2 from "./Misc/卫士2.mjs";
import 鸡 from "./Provinces/鸡.mjs";
import 鹿 from "./Provinces/鹿.mjs";
import 鹿1 from "./Provinces/鹿1.mjs";
import 猪 from "./Provinces/猪.mjs";
import 牛 from "./Provinces/牛.mjs";
import 羊 from "./Provinces/羊.mjs";
import 狼 from "./Provinces/狼.mjs";
import 恶狼 from "./SerpantValley/恶狼.mjs";
import 蛤蟆 from "./Provinces/蛤蟆.mjs";
import 蛤蟆0 from "./Provinces/蛤蟆0.mjs";
import 稻草人 from "./Provinces/稻草人.mjs";
import 稻草人0 from "./Provinces/稻草人0.mjs";
import 稻草人1 from "./Provinces/稻草人1.mjs";
import 多钩猫 from "./Provinces/多钩猫.mjs";
import 多钩猫0 from "./Provinces/多钩猫0.mjs";
import 钉耙猫 from "./Provinces/钉耙猫.mjs";
import 钉耙猫0 from "./Provinces/钉耙猫0.mjs";
import 毒蜘蛛 from "./Provinces/毒蜘蛛.mjs";
import 食人花 from "./Provinces/食人花.mjs";
import 半兽人 from "./Provinces/半兽人.mjs";
import 半兽人0 from "./Provinces/半兽人0.mjs";
import 半兽战士 from "./Provinces/半兽战士.mjs";
import 半兽战士0 from "./Provinces/半兽战士0.mjs";
import 半兽勇士 from "./Provinces/半兽勇士.mjs";
import 半兽勇士1 from "./Provinces/半兽勇士1.mjs";
import 半兽勇士2 from "./Provinces/半兽勇士2.mjs";
import 森林雪人 from "./Provinces/森林雪人.mjs";
import 森林雪人0 from "./Provinces/森林雪人0.mjs";
import 林中虎 from "./Provinces/林中虎.mjs";
import 栗子树 from "./Provinces/栗子树.mjs";
import 栗子树1 from "./Provinces/栗子树1.mjs";
import 栗子树2 from "./Provinces/栗子树2.mjs";
import 乌木树 from "./Provinces/乌木树.mjs";
import 樱桃树 from "./Provinces/樱桃树.mjs";
import 巨型蘑菇 from "./Provinces/巨型蘑菇.mjs";
import 红蛇 from "./Provinces/红蛇.mjs";
import 红蛇0 from "./Provinces/红蛇0.mjs";
import 赤色毒蛇 from "./Provinces/赤色毒蛇.mjs";
import 虎蛇 from "./Provinces/虎蛇.mjs";
import 虎蛇0 from "./Provinces/虎蛇0.mjs";
import 斑纹虎蛇 from "./Provinces/斑纹虎蛇.mjs";
import 多角虫 from "./Provinces/多角虫.mjs";
import 多角虫0 from "./Provinces/多角虫0.mjs";
import 盔甲虫 from "./Provinces/盔甲虫.mjs";
import 盔甲虫0 from "./Provinces/盔甲虫0.mjs";
import 猎鹰 from "./Provinces/猎鹰.mjs";
import 猎鹰0 from "./Provinces/猎鹰0.mjs";
import 沙虫 from "./Provinces/沙虫.mjs";
import 巨型多角虫 from "./Provinces/巨型多角虫.mjs";
import 巨型多角虫1 from "./Provinces/巨型多角虫1.mjs";
import 山洞蝙蝠 from "./BichonProvince/OmaCave/山洞蝙蝠.mjs";
import 山洞蝙蝠0 from "./BichonProvince/OmaCave/山洞蝙蝠0.mjs";
import 洞蛆 from "./BichonProvince/OmaCave/洞蛆.mjs";
import 蝎子 from "./BichonProvince/OmaCave/蝎子.mjs";
import 骷髅 from "./BichonProvince/OmaCave/骷髅.mjs";
import 骷髅0 from "./BichonProvince/OmaCave/骷髅0.mjs";
import 掷斧骷髅 from "./BichonProvince/OmaCave/掷斧骷髅.mjs";
import 掷斧骷髅0 from "./BichonProvince/OmaCave/掷斧骷髅0.mjs";
import 掷斧骷髅9 from "./BichonProvince/OmaCave/掷斧骷髅9.mjs";
import 骷髅战士 from "./BichonProvince/OmaCave/骷髅战士.mjs";
import 骷髅战士0 from "./BichonProvince/OmaCave/骷髅战士0.mjs";
import 骷髅战将 from "./BichonProvince/OmaCave/骷髅战将.mjs";
import 骷髅战将0 from "./BichonProvince/OmaCave/骷髅战将0.mjs";
import 骷髅精灵 from "./BichonProvince/OmaCave/骷髅精灵.mjs";
import 骷髅精灵1 from "./BichonProvince/OmaCave/骷髅精灵1.mjs";
import 骷髅精灵2 from "./BichonProvince/OmaCave/骷髅精灵2.mjs";
import 骷髅精灵9 from "./BichonProvince/OmaCave/骷髅精灵9.mjs";
import 远古掷斧骷髅 from "./AncientCaves/OmaCavern/远古掷斧骷髅.mjs";
import 远古掷斧骷髅0 from "./AncientCaves/OmaCavern/远古掷斧骷髅0.mjs";
import 远古骷髅 from "./AncientCaves/OmaCavern/远古骷髅.mjs";
import 远古骷髅0 from "./AncientCaves/OmaCavern/远古骷髅0.mjs";
import 远古骷髅战士 from "./AncientCaves/OmaCavern/远古骷髅战士.mjs";
import 远古骷髅战士0 from "./AncientCaves/OmaCavern/远古骷髅战士0.mjs";
import 远古骷髅战将 from "./AncientCaves/OmaCavern/远古骷髅战将.mjs";
import 远古骷髅战将0 from "./AncientCaves/OmaCavern/远古骷髅战将0.mjs";
import 远古骷髅精灵 from "./AncientCaves/OmaCavern/远古骷髅精灵.mjs";
import 萨满僵尸1 from "./BichonProvince/DeadMine/萨满僵尸1.mjs";
import 萨满僵尸10 from "./BichonProvince/DeadMine/萨满僵尸10.mjs";
import 钻地僵尸2 from "./BichonProvince/DeadMine/钻地僵尸2.mjs";
import 钻地僵尸20 from "./BichonProvince/DeadMine/钻地僵尸20.mjs";
import 蹒跚僵尸3 from "./BichonProvince/DeadMine/蹒跚僵尸3.mjs";
import 蹒跚僵尸30 from "./BichonProvince/DeadMine/蹒跚僵尸30.mjs";
import 石肤僵尸4 from "./BichonProvince/DeadMine/石肤僵尸4.mjs";
import 石肤僵尸40 from "./BichonProvince/DeadMine/石肤僵尸40.mjs";
import 爬行僵尸5 from "./BichonProvince/DeadMine/爬行僵尸5.mjs";
import 爬行僵尸50 from "./BichonProvince/DeadMine/爬行僵尸50.mjs";
import 尸王 from "./BichonProvince/DeadMine/尸王.mjs";
import 尸王2 from "./BichonProvince/DeadMine/尸王2.mjs";
import 僵尸神父 from "./BichonProvince/DeadMine/僵尸神父.mjs";
import 僵尸神父0 from "./BichonProvince/DeadMine/僵尸神父0.mjs";
import 蹒跚僵尸 from "./BichonProvince/DeadMine/蹒跚僵尸.mjs";
import 蹒跚僵尸0 from "./BichonProvince/DeadMine/蹒跚僵尸0.mjs";
import 石肤僵尸 from "./BichonProvince/DeadMine/石肤僵尸.mjs";
import 石肤僵尸0 from "./BichonProvince/DeadMine/石肤僵尸0.mjs";
import 爬行僵尸 from "./BichonProvince/DeadMine/爬行僵尸.mjs";
import 爬行僵尸0 from "./BichonProvince/DeadMine/爬行僵尸0.mjs";
import 萨满僵尸 from "./BichonProvince/DeadMine/萨满僵尸.mjs";
import 萨满僵尸0 from "./BichonProvince/DeadMine/萨满僵尸0.mjs";
import 白蛇 from "./SerpantValley/ViperCave/白蛇.mjs";
import 碧蓝幼蛇 from "./SerpantValley/ViperCave/碧蓝幼蛇.mjs";
import 碧蓝幼蛇0 from "./SerpantValley/ViperCave/碧蓝幼蛇0.mjs";
import 黄金幼蛇 from "./SerpantValley/ViperCave/黄金幼蛇.mjs";
import 黄金幼蛇0 from "./SerpantValley/ViperCave/黄金幼蛇0.mjs";
import 蛇王护卫 from "./SerpantValley/ViperCave/蛇王护卫.mjs";
import 浮龙金蛇 from "./SerpantValley/ViperCave/浮龙金蛇.mjs";
import 黑色恶蛆 from "./MongchonProvince/BugCave/黑色恶蛆.mjs";
import 黑色恶蛆0 from "./MongchonProvince/BugCave/黑色恶蛆0.mjs";
import 蜈蚣 from "./MongchonProvince/BugCave/蜈蚣.mjs";
import 蜈蚣0 from "./MongchonProvince/BugCave/蜈蚣0.mjs";
import 巨型蠕虫 from "./MongchonProvince/BugCave/巨型蠕虫.mjs";
import 巨型蠕虫0 from "./MongchonProvince/BugCave/巨型蠕虫0.mjs";
import 跳跳蜂 from "./MongchonProvince/BugCave/跳跳蜂.mjs";
import 跳跳蜂0 from "./MongchonProvince/BugCave/跳跳蜂0.mjs";
import 钳虫 from "./MongchonProvince/BugCave/钳虫.mjs";
import 钳虫0 from "./MongchonProvince/BugCave/钳虫0.mjs";
import 邪恶钳虫 from "./MongchonProvince/BugCave/邪恶钳虫.mjs";
import 邪恶钳虫1 from "./MongchonProvince/BugCave/邪恶钳虫1.mjs";
import 邪恶钳虫2 from "./MongchonProvince/BugCave/邪恶钳虫2.mjs";
import 邪恶钳虫9 from "./MongchonProvince/BugCave/邪恶钳虫9.mjs";
import 触龙神 from "./MongchonProvince/BugCave/触龙神.mjs";
import 楔蛾 from "./MongchonProvince/StoneTomb/楔蛾.mjs";
import 小蝙蝠 from "./MongchonProvince/StoneTomb/小蝙蝠.mjs";
import 角蝇 from "./MongchonProvince/StoneTomb/角蝇.mjs";
import 红野猪 from "./MongchonProvince/StoneTomb/红野猪.mjs";
import 红野猪0 from "./MongchonProvince/StoneTomb/红野猪0.mjs";
import 红野猪3 from "./MongchonProvince/StoneTomb/红野猪3.mjs";
import 黑野猪 from "./MongchonProvince/StoneTomb/黑野猪.mjs";
import 黑野猪0 from "./MongchonProvince/StoneTomb/黑野猪0.mjs";
import 黑野猪3 from "./MongchonProvince/StoneTomb/黑野猪3.mjs";
import 白野猪 from "./MongchonProvince/StoneTomb/白野猪.mjs";
import 白野猪0 from "./MongchonProvince/StoneTomb/白野猪0.mjs";
import 白野猪1 from "./MongchonProvince/StoneTomb/白野猪1.mjs";
import 蝎蛇 from "./MongchonProvince/StoneTomb/蝎蛇.mjs";
import 蝎蛇0 from "./MongchonProvince/StoneTomb/蝎蛇0.mjs";
import 蝎蛇3 from "./MongchonProvince/StoneTomb/蝎蛇3.mjs";
import 邪恶毒蛇 from "./MongchonProvince/StoneTomb/邪恶毒蛇.mjs";
import 邪恶毒蛇1 from "./MongchonProvince/StoneTomb/邪恶毒蛇1.mjs";
import 远古黑色恶蛆 from "./AncientCaves/StoneTemple/远古黑色恶蛆.mjs";
import 远古黑色恶蛆0 from "./AncientCaves/StoneTemple/远古黑色恶蛆0.mjs";
import 远古蝎蛇 from "./AncientCaves/StoneTemple/远古蝎蛇.mjs";
import 远古蝎蛇0 from "./AncientCaves/StoneTemple/远古蝎蛇0.mjs";
import 远古红猪 from "./AncientCaves/StoneTemple/远古红猪.mjs";
import 远古红猪0 from "./AncientCaves/StoneTemple/远古红猪0.mjs";
import 远古黑猪 from "./AncientCaves/StoneTemple/远古黑猪.mjs";
import 远古黑猪0 from "./AncientCaves/StoneTemple/远古黑猪0.mjs";
import 远古白猪 from "./AncientCaves/StoneTemple/远古白猪.mjs";
import 远古猪王 from "./AncientCaves/StoneTemple/远古猪王.mjs";
import 大老鼠 from "./MongchonProvince/Zuma/大老鼠.mjs";
import 大老鼠0 from "./MongchonProvince/Zuma/大老鼠0.mjs";
import 祖玛弓箭手 from "./MongchonProvince/Zuma/祖玛弓箭手.mjs";
import 祖玛弓箭手0 from "./MongchonProvince/Zuma/祖玛弓箭手0.mjs";
import 祖玛弓箭手3 from "./MongchonProvince/Zuma/祖玛弓箭手3.mjs";
import 祖玛雕像 from "./MongchonProvince/Zuma/祖玛雕像.mjs";
import 祖玛雕像0 from "./MongchonProvince/Zuma/祖玛雕像0.mjs";
import 祖玛雕像3 from "./MongchonProvince/Zuma/祖玛雕像3.mjs";
import 祖玛卫士 from "./MongchonProvince/Zuma/祖玛卫士.mjs";
import 祖玛卫士0 from "./MongchonProvince/Zuma/祖玛卫士0.mjs";
import 祖玛卫士3 from "./MongchonProvince/Zuma/祖玛卫士3.mjs";
import 祖玛卫士00 from "./MongchonProvince/Zuma/祖玛卫士00.mjs";
import 祖玛统领 from "./MongchonProvince/Zuma/祖玛统领.mjs";
import 祖玛教主 from "./MongchonProvince/Zuma/祖玛教主.mjs";
import 祖玛教主9 from "./MongchonProvince/Zuma/祖玛教主9.mjs";
import 远古大老鼠 from "./AncientCaves/ZumaTemple/远古大老鼠.mjs";
import 远古大老鼠0 from "./AncientCaves/ZumaTemple/远古大老鼠0.mjs";
import 远古祖玛弓箭手 from "./AncientCaves/ZumaTemple/远古祖玛弓箭手.mjs";
import 远古祖玛弓箭手0 from "./AncientCaves/ZumaTemple/远古祖玛弓箭手0.mjs";
import 远古祖玛雕像 from "./AncientCaves/ZumaTemple/远古祖玛雕像.mjs";
import 远古祖玛雕像0 from "./AncientCaves/ZumaTemple/远古祖玛雕像0.mjs";
import 远古祖玛卫士 from "./AncientCaves/ZumaTemple/远古祖玛卫士.mjs";
import 远古祖玛卫士0 from "./AncientCaves/ZumaTemple/远古祖玛卫士0.mjs";
import 远古祖玛统领 from "./AncientCaves/ZumaTemple/远古祖玛统领.mjs";
import 赤狐 from "./MongchonProvince/Fox/赤狐.mjs";
import 黑狐 from "./MongchonProvince/Fox/黑狐.mjs";
import 素狐 from "./MongchonProvince/Fox/素狐.mjs";
import 狐月天珠 from "./MongchonProvince/Fox/狐月天珠.mjs";
import 电元素 from "./MongchonProvince/Fox/电元素.mjs";
import 气元素 from "./MongchonProvince/Fox/气元素.mjs";
import 狐月蓝蛙 from "./WoomyonWoods/InsectCave/狐月蓝蛙.mjs";
import 狐月褐蛙 from "./WoomyonWoods/InsectCave/狐月褐蛙.mjs";
import 狐月火蛙 from "./WoomyonWoods/InsectCave/狐月火蛙.mjs";
import 血蛙 from "./WoomyonWoods/InsectCave/血蛙.mjs";
import 血蛙0 from "./WoomyonWoods/InsectCave/血蛙0.mjs";
import 魔眼 from "./WoomyonWoods/InsectCave/魔眼.mjs";
import 魔眼0 from "./WoomyonWoods/InsectCave/魔眼0.mjs";
import 碧蓝魔眼 from "./WoomyonWoods/InsectCave/碧蓝魔眼.mjs";
import 碧蓝魔眼0 from "./WoomyonWoods/InsectCave/碧蓝魔眼0.mjs";
import 虎虫 from "./WoomyonWoods/InsectCave/虎虫.mjs";
import 虎虫0 from "./WoomyonWoods/InsectCave/虎虫0.mjs";
import 紫虎虫 from "./WoomyonWoods/InsectCave/紫虎虫.mjs";
import 紫虎虫0 from "./WoomyonWoods/InsectCave/紫虎虫0.mjs";
import 狂热火蜥蜴 from "./WoomyonWoods/InsectCave/狂热火蜥蜴.mjs";
import 暗黑战士 from "./WoomyonWoods/WoomaTemple/暗黑战士.mjs";
import 暗黑战士0 from "./WoomyonWoods/WoomaTemple/暗黑战士0.mjs";
import 粪虫 from "./WoomyonWoods/WoomaTemple/粪虫.mjs";
import 粪虫0 from "./WoomyonWoods/WoomaTemple/粪虫0.mjs";
import 沃玛军士 from "./WoomyonWoods/WoomaTemple/沃玛军士.mjs";
import 沃玛军士0 from "./WoomyonWoods/WoomaTemple/沃玛军士0.mjs";
import 沃玛战士 from "./WoomyonWoods/WoomaTemple/沃玛战士.mjs";
import 沃玛战士0 from "./WoomyonWoods/WoomaTemple/沃玛战士0.mjs";
import 沃玛勇士 from "./WoomyonWoods/WoomaTemple/沃玛勇士.mjs";
import 沃玛勇士0 from "./WoomyonWoods/WoomaTemple/沃玛勇士0.mjs";
import 沃玛卫士 from "./WoomyonWoods/WoomaTemple/沃玛卫士.mjs";
import 沃玛卫士1 from "./WoomyonWoods/WoomaTemple/沃玛卫士1.mjs";
import 沃玛卫士2 from "./WoomyonWoods/WoomaTemple/沃玛卫士2.mjs";
import 沃玛教主 from "./WoomyonWoods/WoomaTemple/沃玛教主.mjs";
import 沃玛教主1 from "./WoomyonWoods/WoomaTemple/沃玛教主1.mjs";
import 远古沃玛军士 from "./AncientCaves/WoomaTemple/远古沃玛军士.mjs";
import 远古沃玛战士 from "./AncientCaves/WoomaTemple/远古沃玛战士.mjs";
import 远古沃玛勇士 from "./AncientCaves/WoomaTemple/远古沃玛勇士.mjs";
import 远古火焰沃玛 from "./AncientCaves/WoomaTemple/远古火焰沃玛.mjs";
import 远古沃玛卫士 from "./AncientCaves/WoomaTemple/远古沃玛卫士.mjs";
import 远古沃玛教主 from "./AncientCaves/WoomaTemple/远古沃玛教主.mjs";
import 邪恶钳虫20 from "./Castle-Gi/BDD/邪恶钳虫20.mjs";
import 邪恶钳虫21 from "./Castle-Gi/BDD/邪恶钳虫21.mjs";
import 邪恶毒蛇20 from "./Castle-Gi/BDD/邪恶毒蛇20.mjs";
import 邪恶毒蛇21 from "./Castle-Gi/BDD/邪恶毒蛇21.mjs";
import 尸王20 from "./Castle-Gi/BDD/尸王20.mjs";
import 尸王21 from "./Castle-Gi/BDD/尸王21.mjs";
import 祖玛弓箭手20 from "./Castle-Gi/BDD/祖玛弓箭手20.mjs";
import 祖玛弓箭手21 from "./Castle-Gi/BDD/祖玛弓箭手21.mjs";
import 祖玛雕像20 from "./Castle-Gi/BDD/祖玛雕像20.mjs";
import 祖玛雕像21 from "./Castle-Gi/BDD/祖玛雕像21.mjs";
import 祖玛卫士20 from "./Castle-Gi/BDD/祖玛卫士20.mjs";
import 祖玛卫士21 from "./Castle-Gi/BDD/祖玛卫士21.mjs";
import 白野猪20 from "./Castle-Gi/BDD/白野猪20.mjs";
import 白野猪21 from "./Castle-Gi/BDD/白野猪21.mjs";
import 虹魔蝎卫 from "./Castle-Gi/BDD/虹魔蝎卫.mjs";
import 虹魔猪卫 from "./Castle-Gi/BDD/虹魔猪卫.mjs";
import 魔化沃玛教主 from "./Castle-Gi/BDD/魔化沃玛教主.mjs";
import 魔化祖玛教主 from "./Castle-Gi/BDD/魔化祖玛教主.mjs";
import 黑暗魔王 from "./Castle-Gi/BDD/黑暗魔王.mjs";
import 血之僵尸 from "./TaoVillage/MineralMines/血之僵尸.mjs";
import 血之僵尸0 from "./TaoVillage/MineralMines/血之僵尸0.mjs";
import 被诅咒的萨满 from "./TaoVillage/MineralMines/被诅咒的萨满.mjs";
import 被诅咒的萨满0 from "./TaoVillage/MineralMines/被诅咒的萨满0.mjs";
import 被诅咒的神父 from "./TaoVillage/MineralMines/被诅咒的神父.mjs";
import 被诅咒的神父0 from "./TaoVillage/MineralMines/被诅咒的神父0.mjs";
import 被诅咒的僵尸 from "./TaoVillage/MineralMines/被诅咒的僵尸.mjs";
import 被诅咒的僵尸0 from "./TaoVillage/MineralMines/被诅咒的僵尸0.mjs";
import 游荡恶鬼 from "./TaoVillage/MineralMines/游荡恶鬼.mjs";
import 游荡恶鬼0 from "./TaoVillage/MineralMines/游荡恶鬼0.mjs";
import 石化僵尸 from "./TaoVillage/MineralMines/石化僵尸.mjs";
import 石化僵尸0 from "./TaoVillage/MineralMines/石化僵尸0.mjs";
import 剧毒僵尸 from "./TaoVillage/MineralMines/剧毒僵尸.mjs";
import 剧毒僵尸0 from "./TaoVillage/MineralMines/剧毒僵尸0.mjs";
import 巨型尸王 from "./TaoVillage/MineralMines/巨型尸王.mjs";
import 幻影蜘蛛 from "./TaoVillage/TreePath/RedValley/幻影蜘蛛.mjs";
import 月魔蜘蛛 from "./TaoVillage/TreePath/RedValley/月魔蜘蛛.mjs";
import 天狼蜘蛛 from "./TaoVillage/TreePath/RedValley/天狼蜘蛛.mjs";
import 天狼蜘蛛0 from "./TaoVillage/TreePath/RedValley/天狼蜘蛛0.mjs";
import 天狼蜘蛛3 from "./TaoVillage/TreePath/RedValley/天狼蜘蛛3.mjs";
import 钢牙蜘蛛 from "./TaoVillage/TreePath/RedValley/钢牙蜘蛛.mjs";
import 钢牙蜘蛛0 from "./TaoVillage/TreePath/RedValley/钢牙蜘蛛0.mjs";
import 钢牙蜘蛛3 from "./TaoVillage/TreePath/RedValley/钢牙蜘蛛3.mjs";
import 黑锷蜘蛛 from "./TaoVillage/TreePath/RedValley/黑锷蜘蛛.mjs";
import 黑锷蜘蛛0 from "./TaoVillage/TreePath/RedValley/黑锷蜘蛛0.mjs";
import 黑锷蜘蛛3 from "./TaoVillage/TreePath/RedValley/黑锷蜘蛛3.mjs";
import 花吻蜘蛛 from "./TaoVillage/TreePath/RedValley/花吻蜘蛛.mjs";
import 花吻蜘蛛0 from "./TaoVillage/TreePath/RedValley/花吻蜘蛛0.mjs";
import 花吻蜘蛛3 from "./TaoVillage/TreePath/RedValley/花吻蜘蛛3.mjs";
import 血巨人 from "./TaoVillage/TreePath/RedValley/血巨人.mjs";
import 血巨人0 from "./TaoVillage/TreePath/RedValley/血巨人0.mjs";
import 血巨人3 from "./TaoVillage/TreePath/RedValley/血巨人3.mjs";
import 邪恶巨人 from "./TaoVillage/TreePath/RedValley/邪恶巨人.mjs";
import 邪恶巨人0 from "./TaoVillage/TreePath/RedValley/邪恶巨人0.mjs";
import 绿巨人 from "./TaoVillage/TreePath/RedValley/绿巨人.mjs";
import 红巨人 from "./TaoVillage/TreePath/RedValley/红巨人.mjs";
import 水晶蜘蛛 from "./TaoVillage/TreePath/RedValley/水晶蜘蛛.mjs";
import 赤月恶魔 from "./TaoVillage/TreePath/RedValley/赤月恶魔.mjs";
import 赤月恶魔1 from "./TaoVillage/TreePath/RedValley/赤月恶魔1.mjs";
import 邪恶巨人王 from "./TaoVillage/TreePath/RedValley/邪恶巨人王.mjs";
import 太阴月魔 from "./TaoVillage/TreePath/Lunar/太阴月魔.mjs";
import 蓝背蜘蛛 from "./TaoVillage/TreePath/Lunar/蓝背蜘蛛.mjs";
import 剧毒蓝背蛛 from "./TaoVillage/TreePath/Lunar/剧毒蓝背蛛.mjs";
import 太阴黑锷蛛 from "./TaoVillage/TreePath/Lunar/太阴黑锷蛛.mjs";
import 太阴花吻蛛 from "./TaoVillage/TreePath/Lunar/太阴花吻蛛.mjs";
import 太阴水晶蛛 from "./TaoVillage/TreePath/Lunar/太阴水晶蛛.mjs";
import GreaterWeaver from "./TaoVillage/TreePath/Lunar/GreaterWeaver.mjs";
import 巨镰蜘蛛 from "./TaoVillage/TreePath/Lunar/巨镰蜘蛛.mjs";
import 金杖蜘蛛 from "./TaoVillage/TreePath/Lunar/金杖蜘蛛.mjs";
import 鸟人像 from "./TaoVillage/TreePath/Lunar/鸟人像.mjs";
import 石魔鬼尊 from "./TaoVillage/TreePath/Lunar/石魔鬼尊.mjs";
import 恶灵尸王 from "./PranjaIsland/PranjaStoneCave/恶灵尸王.mjs";
import 恶灵尸王0 from "./PranjaIsland/PranjaStoneCave/恶灵尸王0.mjs";
import 恶灵僵尸 from "./PranjaIsland/PranjaStoneCave/恶灵僵尸.mjs";
import 恶灵僵尸0 from "./PranjaIsland/PranjaStoneCave/恶灵僵尸0.mjs";
import 骷髅弓箭手 from "./PranjaIsland/PranjaStoneCave/骷髅弓箭手.mjs";
import 骷髅弓箭手0 from "./PranjaIsland/PranjaStoneCave/骷髅弓箭手0.mjs";
import 骷髅刀斧手 from "./PranjaIsland/PranjaStoneCave/骷髅刀斧手.mjs";
import 骷髅刀斧手0 from "./PranjaIsland/PranjaStoneCave/骷髅刀斧手0.mjs";
import 骷髅长枪兵 from "./PranjaIsland/PranjaStoneCave/骷髅长枪兵.mjs";
import 骷髅长枪兵0 from "./PranjaIsland/PranjaStoneCave/骷髅长枪兵0.mjs";
import 骷髅锤兵 from "./PranjaIsland/PranjaStoneCave/骷髅锤兵.mjs";
import 骷髅锤兵0 from "./PranjaIsland/PranjaStoneCave/骷髅锤兵0.mjs";
import 骸骨盘王 from "./PranjaIsland/PranjaStoneCave/骸骨盘王.mjs";
import 远古恶灵尸王 from "./AncientCaves/Prajna/远古恶灵尸王.mjs";
import 远古恶灵僵尸 from "./AncientCaves/Prajna/远古恶灵僵尸.mjs";
import 远古骷髅弓箭手 from "./AncientCaves/Prajna/远古骷髅弓箭手.mjs";
import 远古骷髅刀斧手 from "./AncientCaves/Prajna/远古骷髅刀斧手.mjs";
import 远古骷髅长枪兵 from "./AncientCaves/Prajna/远古骷髅长枪兵.mjs";
import 远古骷髅锤兵 from "./AncientCaves/Prajna/远古骷髅锤兵.mjs";
import 远古骸骨盘王 from "./AncientCaves/Prajna/远古骸骨盘王.mjs";
import 牛头魔 from "./PranjaIsland/PranjaTemple/牛头魔.mjs";
import 牛头魔0 from "./PranjaIsland/PranjaTemple/牛头魔0.mjs";
import 冰牛魔 from "./PranjaIsland/PranjaTemple/冰牛魔.mjs";
import 冰牛魔0 from "./PranjaIsland/PranjaTemple/冰牛魔0.mjs";
import 电光牛魔 from "./PranjaIsland/PranjaTemple/电光牛魔.mjs";
import 电光牛魔0 from "./PranjaIsland/PranjaTemple/电光牛魔0.mjs";
import 风之牛魔 from "./PranjaIsland/PranjaTemple/风之牛魔.mjs";
import 风之牛魔0 from "./PranjaIsland/PranjaTemple/风之牛魔0.mjs";
import 火焰牛魔 from "./PranjaIsland/PranjaTemple/火焰牛魔.mjs";
import 火焰牛魔0 from "./PranjaIsland/PranjaTemple/火焰牛魔0.mjs";
import 右护法 from "./PranjaIsland/PranjaTemple/右护法.mjs";
import 右护法0 from "./PranjaIsland/PranjaTemple/右护法0.mjs";
import 左护法 from "./PranjaIsland/PranjaTemple/左护法.mjs";
import 左护法0 from "./PranjaIsland/PranjaTemple/左护法0.mjs";
import 邪牛天王 from "./PranjaIsland/PranjaTemple/邪牛天王.mjs";
import 魔龙刀斧手 from "./PastBichon/OmaValley/魔龙刀斧手.mjs";
import 魔龙刀斧手0 from "./PastBichon/OmaValley/魔龙刀斧手0.mjs";
import 魔龙刀兵 from "./PastBichon/OmaValley/魔龙刀兵.mjs";
import 魔龙刀兵0 from "./PastBichon/OmaValley/魔龙刀兵0.mjs";
import 魔龙射手 from "./PastBichon/OmaValley/魔龙射手.mjs";
import 魔龙射手0 from "./PastBichon/OmaValley/魔龙射手0.mjs";
import 魔龙巨蛾 from "./PastBichon/OmaValley/魔龙巨蛾.mjs";
import 魔龙巨蛾0 from "./PastBichon/OmaValley/魔龙巨蛾0.mjs";
import 魔龙战将 from "./PastBichon/OmaValley/魔龙战将.mjs";
import 魔龙战将0 from "./PastBichon/OmaValley/魔龙战将0.mjs";
import 魔龙力士 from "./PastBichon/OmaValley/魔龙力士.mjs";
import 魔龙力士0 from "./PastBichon/OmaValley/魔龙力士0.mjs";
import 阴之石碑 from "./PastBichon/OmaValley/阴之石碑.mjs";
import 阳之石碑 from "./PastBichon/OmaValley/阳之石碑.mjs";
import 凰天魔神 from "./PastBichon/OmaValley/凰天魔神.mjs";
import 凰天魔魂 from "./BichonProvince/OmaCave/凰天魔魂.mjs";
import ManectricHammer from "./Unused/IceHell/ManectricHammer.mjs";
import ManectricClub from "./Unused/IceHell/ManectricClub.mjs";
import ManectricClaw from "./Unused/IceHell/ManectricClaw.mjs";
import ManectricSlave from "./Unused/IceHell/ManectricSlave.mjs";
import Demon1 from "./WasteLand/HellCavern/Demon1.mjs";
import Demon2 from "./WasteLand/HellCavern/Demon2.mjs";
import ManectricBlest from "./Unused/IceHell/ManectricBlest.mjs";
import ManectricKing from "./Unused/IceHell/ManectricKing.mjs";
import 梦魇 from "./WasteLand/RedCavern/梦魇.mjs";
import 怨恶 from "./WasteLand/RedCavern/怨恶.mjs";
import HellSlasher from "./WasteLand/HellCavern/HellSlasher.mjs";
import HellPirate from "./WasteLand/HellCavern/HellPirate.mjs";
import HellCannibal from "./WasteLand/HellCavern/HellCannibal.mjs";
import HellBolt from "./WasteLand/HellCavern/HellBolt.mjs";
import WitchDoctor from "./WasteLand/HellCavern/WitchDoctor.mjs";
import CaveWitch from "./WasteLand/HellCavern/CaveWitch.mjs";
import HellKeeper from "./WasteLand/HellCavern/HellKeeper.mjs";
import 白象 from "./DeadForest/Ruins/白象.mjs";
import TucsonEgg from "./MongchonProvince/Swamp/TucsonEgg.mjs";
import YoungTucson from "./MongchonProvince/Swamp/YoungTucson.mjs";
import VisceralWorm2 from "./MongchonProvince/Swamp/VisceralWorm2.mjs";
import SandSnail from "./MongchonProvince/Swamp/SandSnail.mjs";
import CannibalTentacles from "./MongchonProvince/Swamp/CannibalTentacles.mjs";
import Tucson from "./MongchonProvince/Swamp/Tucson.mjs";
import TucsonFighter from "./MongchonProvince/Swamp/TucsonFighter.mjs";
import TucsonMage from "./MongchonProvince/Swamp/TucsonMage.mjs";
import TucsonWarrior from "./MongchonProvince/Swamp/TucsonWarrior.mjs";
import GeneralTucson from "./MongchonProvince/Swamp/GeneralTucson.mjs";
import HellKnight1 from "./Unused/HellFire/HellKnight1.mjs";
import HellKnight2 from "./Unused/HellFire/HellKnight2.mjs";
import HellKnight3 from "./Unused/HellFire/HellKnight3.mjs";
import HellBomb1 from "./Unused/HellFire/HellBomb1.mjs";
import HellBomb2 from "./Unused/HellFire/HellBomb2.mjs";
import HornedArcher from "./Unused/Horned/HornedArcher.mjs";
import HornedCommander from "./Unused/Horned/HornedCommander.mjs";
import HornedMage from "./Unused/Horned/HornedMage.mjs";
import HornedWarrior from "./Unused/Horned/HornedWarrior.mjs";
import BoulderSpirit from "./Unused/Horned/BoulderSpirit.mjs";
import Ancient_ZumaTaurus from "./AncientCaves/ZumaTemple/Ancient_ZumaTaurus.mjs";
import Frozen_ZumaStatue from "./TaoVillage/TreePath/Lunar/Frozen_ZumaStatue.mjs";
import Frozen_ZumaGuardian from "./TaoVillage/TreePath/Lunar/Frozen_ZumaGuardian.mjs";
import Frozen_RedZuma from "./TaoVillage/TreePath/Lunar/Frozen_RedZuma.mjs";

export default function Init(context: CS.Daboluo.Mir2.MirScripts.ServerInitializationScriptContext) {
    context.AddMonsterDropDefinitions("卫士2", 卫士2);
    context.AddMonsterDropDefinitions("鸡", 鸡);
    context.AddMonsterDropDefinitions("鹿", 鹿);
    context.AddMonsterDropDefinitions("鹿1", 鹿1);
    context.AddMonsterDropDefinitions("猪", 猪);
    context.AddMonsterDropDefinitions("牛", 牛);
    context.AddMonsterDropDefinitions("羊", 羊);
    context.AddMonsterDropDefinitions("狼", 狼);
    context.AddMonsterDropDefinitions("恶狼", 恶狼);
    context.AddMonsterDropDefinitions("蛤蟆", 蛤蟆);
    context.AddMonsterDropDefinitions("蛤蟆0", 蛤蟆0);
    context.AddMonsterDropDefinitions("稻草人", 稻草人);
    context.AddMonsterDropDefinitions("稻草人0", 稻草人0);
    context.AddMonsterDropDefinitions("稻草人1", 稻草人1);
    context.AddMonsterDropDefinitions("多钩猫", 多钩猫);
    context.AddMonsterDropDefinitions("多钩猫0", 多钩猫0);
    context.AddMonsterDropDefinitions("钉耙猫", 钉耙猫);
    context.AddMonsterDropDefinitions("钉耙猫0", 钉耙猫0);
    context.AddMonsterDropDefinitions("毒蜘蛛", 毒蜘蛛);
    context.AddMonsterDropDefinitions("食人花", 食人花);
    context.AddMonsterDropDefinitions("半兽人", 半兽人);
    context.AddMonsterDropDefinitions("半兽人0", 半兽人0);
    context.AddMonsterDropDefinitions("半兽战士", 半兽战士);
    context.AddMonsterDropDefinitions("半兽战士0", 半兽战士0);
    context.AddMonsterDropDefinitions("半兽勇士", 半兽勇士);
    context.AddMonsterDropDefinitions("半兽勇士1", 半兽勇士1);
    context.AddMonsterDropDefinitions("半兽勇士2", 半兽勇士2);
    context.AddMonsterDropDefinitions("森林雪人", 森林雪人);
    context.AddMonsterDropDefinitions("森林雪人0", 森林雪人0);
    context.AddMonsterDropDefinitions("林中虎", 林中虎);
    context.AddMonsterDropDefinitions("栗子树", 栗子树);
    context.AddMonsterDropDefinitions("栗子树1", 栗子树1);
    context.AddMonsterDropDefinitions("栗子树2", 栗子树2);
    context.AddMonsterDropDefinitions("乌木树", 乌木树);
    context.AddMonsterDropDefinitions("樱桃树", 樱桃树);
    context.AddMonsterDropDefinitions("巨型蘑菇", 巨型蘑菇);
    context.AddMonsterDropDefinitions("红蛇", 红蛇);
    context.AddMonsterDropDefinitions("红蛇0", 红蛇0);
    context.AddMonsterDropDefinitions("赤色毒蛇", 赤色毒蛇);
    context.AddMonsterDropDefinitions("虎蛇", 虎蛇);
    context.AddMonsterDropDefinitions("虎蛇0", 虎蛇0);
    context.AddMonsterDropDefinitions("斑纹虎蛇", 斑纹虎蛇);
    context.AddMonsterDropDefinitions("多角虫", 多角虫);
    context.AddMonsterDropDefinitions("多角虫0", 多角虫0);
    context.AddMonsterDropDefinitions("盔甲虫", 盔甲虫);
    context.AddMonsterDropDefinitions("盔甲虫0", 盔甲虫0);
    context.AddMonsterDropDefinitions("猎鹰", 猎鹰);
    context.AddMonsterDropDefinitions("猎鹰0", 猎鹰0);
    context.AddMonsterDropDefinitions("沙虫", 沙虫);
    context.AddMonsterDropDefinitions("巨型多角虫", 巨型多角虫);
    context.AddMonsterDropDefinitions("巨型多角虫1", 巨型多角虫1);
    context.AddMonsterDropDefinitions("山洞蝙蝠", 山洞蝙蝠);
    context.AddMonsterDropDefinitions("山洞蝙蝠0", 山洞蝙蝠0);
    context.AddMonsterDropDefinitions("洞蛆", 洞蛆);
    context.AddMonsterDropDefinitions("蝎子", 蝎子);
    context.AddMonsterDropDefinitions("骷髅", 骷髅);
    context.AddMonsterDropDefinitions("骷髅0", 骷髅0);
    context.AddMonsterDropDefinitions("掷斧骷髅", 掷斧骷髅);
    context.AddMonsterDropDefinitions("掷斧骷髅0", 掷斧骷髅0);
    context.AddMonsterDropDefinitions("掷斧骷髅9", 掷斧骷髅9);
    context.AddMonsterDropDefinitions("骷髅战士", 骷髅战士);
    context.AddMonsterDropDefinitions("骷髅战士0", 骷髅战士0);
    context.AddMonsterDropDefinitions("骷髅战将", 骷髅战将);
    context.AddMonsterDropDefinitions("骷髅战将0", 骷髅战将0);
    context.AddMonsterDropDefinitions("骷髅精灵", 骷髅精灵);
    context.AddMonsterDropDefinitions("骷髅精灵1", 骷髅精灵1);
    context.AddMonsterDropDefinitions("骷髅精灵2", 骷髅精灵2);
    context.AddMonsterDropDefinitions("骷髅精灵9", 骷髅精灵9);
    context.AddMonsterDropDefinitions("远古掷斧骷髅", 远古掷斧骷髅);
    context.AddMonsterDropDefinitions("远古掷斧骷髅0", 远古掷斧骷髅0);
    context.AddMonsterDropDefinitions("远古骷髅", 远古骷髅);
    context.AddMonsterDropDefinitions("远古骷髅0", 远古骷髅0);
    context.AddMonsterDropDefinitions("远古骷髅战士", 远古骷髅战士);
    context.AddMonsterDropDefinitions("远古骷髅战士0", 远古骷髅战士0);
    context.AddMonsterDropDefinitions("远古骷髅战将", 远古骷髅战将);
    context.AddMonsterDropDefinitions("远古骷髅战将0", 远古骷髅战将0);
    context.AddMonsterDropDefinitions("远古骷髅精灵", 远古骷髅精灵);
    context.AddMonsterDropDefinitions("萨满僵尸1", 萨满僵尸1);
    context.AddMonsterDropDefinitions("萨满僵尸10", 萨满僵尸10);
    context.AddMonsterDropDefinitions("钻地僵尸2", 钻地僵尸2);
    context.AddMonsterDropDefinitions("钻地僵尸20", 钻地僵尸20);
    context.AddMonsterDropDefinitions("蹒跚僵尸3", 蹒跚僵尸3);
    context.AddMonsterDropDefinitions("蹒跚僵尸30", 蹒跚僵尸30);
    context.AddMonsterDropDefinitions("石肤僵尸4", 石肤僵尸4);
    context.AddMonsterDropDefinitions("石肤僵尸40", 石肤僵尸40);
    context.AddMonsterDropDefinitions("爬行僵尸5", 爬行僵尸5);
    context.AddMonsterDropDefinitions("爬行僵尸50", 爬行僵尸50);
    context.AddMonsterDropDefinitions("尸王", 尸王);
    context.AddMonsterDropDefinitions("尸王2", 尸王2);
    context.AddMonsterDropDefinitions("僵尸神父", 僵尸神父);
    context.AddMonsterDropDefinitions("僵尸神父0", 僵尸神父0);
    context.AddMonsterDropDefinitions("蹒跚僵尸", 蹒跚僵尸);
    context.AddMonsterDropDefinitions("蹒跚僵尸0", 蹒跚僵尸0);
    context.AddMonsterDropDefinitions("石肤僵尸", 石肤僵尸);
    context.AddMonsterDropDefinitions("石肤僵尸0", 石肤僵尸0);
    context.AddMonsterDropDefinitions("爬行僵尸", 爬行僵尸);
    context.AddMonsterDropDefinitions("爬行僵尸0", 爬行僵尸0);
    context.AddMonsterDropDefinitions("萨满僵尸", 萨满僵尸);
    context.AddMonsterDropDefinitions("萨满僵尸0", 萨满僵尸0);
    context.AddMonsterDropDefinitions("白蛇", 白蛇);
    context.AddMonsterDropDefinitions("碧蓝幼蛇", 碧蓝幼蛇);
    context.AddMonsterDropDefinitions("碧蓝幼蛇0", 碧蓝幼蛇0);
    context.AddMonsterDropDefinitions("黄金幼蛇", 黄金幼蛇);
    context.AddMonsterDropDefinitions("黄金幼蛇0", 黄金幼蛇0);
    context.AddMonsterDropDefinitions("蛇王护卫", 蛇王护卫);
    context.AddMonsterDropDefinitions("浮龙金蛇", 浮龙金蛇);
    context.AddMonsterDropDefinitions("黑色恶蛆", 黑色恶蛆);
    context.AddMonsterDropDefinitions("黑色恶蛆0", 黑色恶蛆0);
    context.AddMonsterDropDefinitions("蜈蚣", 蜈蚣);
    context.AddMonsterDropDefinitions("蜈蚣0", 蜈蚣0);
    context.AddMonsterDropDefinitions("巨型蠕虫", 巨型蠕虫);
    context.AddMonsterDropDefinitions("巨型蠕虫0", 巨型蠕虫0);
    context.AddMonsterDropDefinitions("跳跳蜂", 跳跳蜂);
    context.AddMonsterDropDefinitions("跳跳蜂0", 跳跳蜂0);
    context.AddMonsterDropDefinitions("钳虫", 钳虫);
    context.AddMonsterDropDefinitions("钳虫0", 钳虫0);
    context.AddMonsterDropDefinitions("邪恶钳虫", 邪恶钳虫);
    context.AddMonsterDropDefinitions("邪恶钳虫1", 邪恶钳虫1);
    context.AddMonsterDropDefinitions("邪恶钳虫2", 邪恶钳虫2);
    context.AddMonsterDropDefinitions("邪恶钳虫9", 邪恶钳虫9);
    context.AddMonsterDropDefinitions("触龙神", 触龙神);
    context.AddMonsterDropDefinitions("楔蛾", 楔蛾);
    context.AddMonsterDropDefinitions("小蝙蝠", 小蝙蝠);
    context.AddMonsterDropDefinitions("角蝇", 角蝇);
    context.AddMonsterDropDefinitions("红野猪", 红野猪);
    context.AddMonsterDropDefinitions("红野猪0", 红野猪0);
    context.AddMonsterDropDefinitions("红野猪3", 红野猪3);
    context.AddMonsterDropDefinitions("黑野猪", 黑野猪);
    context.AddMonsterDropDefinitions("黑野猪0", 黑野猪0);
    context.AddMonsterDropDefinitions("黑野猪3", 黑野猪3);
    context.AddMonsterDropDefinitions("白野猪", 白野猪);
    context.AddMonsterDropDefinitions("白野猪0", 白野猪0);
    context.AddMonsterDropDefinitions("白野猪1", 白野猪1);
    context.AddMonsterDropDefinitions("蝎蛇", 蝎蛇);
    context.AddMonsterDropDefinitions("蝎蛇0", 蝎蛇0);
    context.AddMonsterDropDefinitions("蝎蛇3", 蝎蛇3);
    context.AddMonsterDropDefinitions("邪恶毒蛇", 邪恶毒蛇);
    context.AddMonsterDropDefinitions("邪恶毒蛇1", 邪恶毒蛇1);
    context.AddMonsterDropDefinitions("远古黑色恶蛆", 远古黑色恶蛆);
    context.AddMonsterDropDefinitions("远古黑色恶蛆0", 远古黑色恶蛆0);
    context.AddMonsterDropDefinitions("远古蝎蛇", 远古蝎蛇);
    context.AddMonsterDropDefinitions("远古蝎蛇0", 远古蝎蛇0);
    context.AddMonsterDropDefinitions("远古红猪", 远古红猪);
    context.AddMonsterDropDefinitions("远古红猪0", 远古红猪0);
    context.AddMonsterDropDefinitions("远古黑猪", 远古黑猪);
    context.AddMonsterDropDefinitions("远古黑猪0", 远古黑猪0);
    context.AddMonsterDropDefinitions("远古白猪", 远古白猪);
    context.AddMonsterDropDefinitions("远古猪王", 远古猪王);
    context.AddMonsterDropDefinitions("大老鼠", 大老鼠);
    context.AddMonsterDropDefinitions("大老鼠0", 大老鼠0);
    context.AddMonsterDropDefinitions("祖玛弓箭手", 祖玛弓箭手);
    context.AddMonsterDropDefinitions("祖玛弓箭手0", 祖玛弓箭手0);
    context.AddMonsterDropDefinitions("祖玛弓箭手3", 祖玛弓箭手3);
    context.AddMonsterDropDefinitions("祖玛雕像", 祖玛雕像);
    context.AddMonsterDropDefinitions("祖玛雕像0", 祖玛雕像0);
    context.AddMonsterDropDefinitions("祖玛雕像3", 祖玛雕像3);
    context.AddMonsterDropDefinitions("祖玛卫士", 祖玛卫士);
    context.AddMonsterDropDefinitions("祖玛卫士0", 祖玛卫士0);
    context.AddMonsterDropDefinitions("祖玛卫士3", 祖玛卫士3);
    context.AddMonsterDropDefinitions("祖玛卫士00", 祖玛卫士00);
    context.AddMonsterDropDefinitions("祖玛统领", 祖玛统领);
    context.AddMonsterDropDefinitions("祖玛教主", 祖玛教主);
    context.AddMonsterDropDefinitions("祖玛教主9", 祖玛教主9);
    context.AddMonsterDropDefinitions("远古大老鼠", 远古大老鼠);
    context.AddMonsterDropDefinitions("远古大老鼠0", 远古大老鼠0);
    context.AddMonsterDropDefinitions("远古祖玛弓箭手", 远古祖玛弓箭手);
    context.AddMonsterDropDefinitions("远古祖玛弓箭手0", 远古祖玛弓箭手0);
    context.AddMonsterDropDefinitions("远古祖玛雕像", 远古祖玛雕像);
    context.AddMonsterDropDefinitions("远古祖玛雕像0", 远古祖玛雕像0);
    context.AddMonsterDropDefinitions("远古祖玛卫士", 远古祖玛卫士);
    context.AddMonsterDropDefinitions("远古祖玛卫士0", 远古祖玛卫士0);
    context.AddMonsterDropDefinitions("远古祖玛统领", 远古祖玛统领);
    context.AddMonsterDropDefinitions("赤狐", 赤狐);
    context.AddMonsterDropDefinitions("黑狐", 黑狐);
    context.AddMonsterDropDefinitions("素狐", 素狐);
    context.AddMonsterDropDefinitions("狐月天珠", 狐月天珠);
    context.AddMonsterDropDefinitions("电元素", 电元素);
    context.AddMonsterDropDefinitions("气元素", 气元素);
    context.AddMonsterDropDefinitions("狐月蓝蛙", 狐月蓝蛙);
    context.AddMonsterDropDefinitions("狐月褐蛙", 狐月褐蛙);
    context.AddMonsterDropDefinitions("狐月火蛙", 狐月火蛙);
    context.AddMonsterDropDefinitions("血蛙", 血蛙);
    context.AddMonsterDropDefinitions("血蛙0", 血蛙0);
    context.AddMonsterDropDefinitions("魔眼", 魔眼);
    context.AddMonsterDropDefinitions("魔眼0", 魔眼0);
    context.AddMonsterDropDefinitions("碧蓝魔眼", 碧蓝魔眼);
    context.AddMonsterDropDefinitions("碧蓝魔眼0", 碧蓝魔眼0);
    context.AddMonsterDropDefinitions("虎虫", 虎虫);
    context.AddMonsterDropDefinitions("虎虫0", 虎虫0);
    context.AddMonsterDropDefinitions("紫虎虫", 紫虎虫);
    context.AddMonsterDropDefinitions("紫虎虫0", 紫虎虫0);
    context.AddMonsterDropDefinitions("狂热火蜥蜴", 狂热火蜥蜴);
    context.AddMonsterDropDefinitions("暗黑战士", 暗黑战士);
    context.AddMonsterDropDefinitions("暗黑战士0", 暗黑战士0);
    context.AddMonsterDropDefinitions("粪虫", 粪虫);
    context.AddMonsterDropDefinitions("粪虫0", 粪虫0);
    context.AddMonsterDropDefinitions("沃玛军士", 沃玛军士);
    context.AddMonsterDropDefinitions("沃玛军士0", 沃玛军士0);
    context.AddMonsterDropDefinitions("沃玛战士", 沃玛战士);
    context.AddMonsterDropDefinitions("沃玛战士0", 沃玛战士0);
    context.AddMonsterDropDefinitions("沃玛勇士", 沃玛勇士);
    context.AddMonsterDropDefinitions("沃玛勇士0", 沃玛勇士0);
    context.AddMonsterDropDefinitions("沃玛卫士", 沃玛卫士);
    context.AddMonsterDropDefinitions("沃玛卫士1", 沃玛卫士1);
    context.AddMonsterDropDefinitions("沃玛卫士2", 沃玛卫士2);
    context.AddMonsterDropDefinitions("沃玛教主", 沃玛教主);
    context.AddMonsterDropDefinitions("沃玛教主1", 沃玛教主1);
    context.AddMonsterDropDefinitions("远古沃玛军士", 远古沃玛军士);
    context.AddMonsterDropDefinitions("远古沃玛战士", 远古沃玛战士);
    context.AddMonsterDropDefinitions("远古沃玛勇士", 远古沃玛勇士);
    context.AddMonsterDropDefinitions("远古火焰沃玛", 远古火焰沃玛);
    context.AddMonsterDropDefinitions("远古沃玛卫士", 远古沃玛卫士);
    context.AddMonsterDropDefinitions("远古沃玛教主", 远古沃玛教主);
    context.AddMonsterDropDefinitions("邪恶钳虫20", 邪恶钳虫20);
    context.AddMonsterDropDefinitions("邪恶钳虫21", 邪恶钳虫21);
    context.AddMonsterDropDefinitions("邪恶毒蛇20", 邪恶毒蛇20);
    context.AddMonsterDropDefinitions("邪恶毒蛇21", 邪恶毒蛇21);
    context.AddMonsterDropDefinitions("尸王20", 尸王20);
    context.AddMonsterDropDefinitions("尸王21", 尸王21);
    context.AddMonsterDropDefinitions("祖玛弓箭手20", 祖玛弓箭手20);
    context.AddMonsterDropDefinitions("祖玛弓箭手21", 祖玛弓箭手21);
    context.AddMonsterDropDefinitions("祖玛雕像20", 祖玛雕像20);
    context.AddMonsterDropDefinitions("祖玛雕像21", 祖玛雕像21);
    context.AddMonsterDropDefinitions("祖玛卫士20", 祖玛卫士20);
    context.AddMonsterDropDefinitions("祖玛卫士21", 祖玛卫士21);
    context.AddMonsterDropDefinitions("白野猪20", 白野猪20);
    context.AddMonsterDropDefinitions("白野猪21", 白野猪21);
    context.AddMonsterDropDefinitions("虹魔蝎卫", 虹魔蝎卫);
    context.AddMonsterDropDefinitions("虹魔猪卫", 虹魔猪卫);
    context.AddMonsterDropDefinitions("魔化沃玛教主", 魔化沃玛教主);
    context.AddMonsterDropDefinitions("魔化祖玛教主", 魔化祖玛教主);
    context.AddMonsterDropDefinitions("黑暗魔王", 黑暗魔王);
    context.AddMonsterDropDefinitions("血之僵尸", 血之僵尸);
    context.AddMonsterDropDefinitions("血之僵尸0", 血之僵尸0);
    context.AddMonsterDropDefinitions("被诅咒的萨满", 被诅咒的萨满);
    context.AddMonsterDropDefinitions("被诅咒的萨满0", 被诅咒的萨满0);
    context.AddMonsterDropDefinitions("被诅咒的神父", 被诅咒的神父);
    context.AddMonsterDropDefinitions("被诅咒的神父0", 被诅咒的神父0);
    context.AddMonsterDropDefinitions("被诅咒的僵尸", 被诅咒的僵尸);
    context.AddMonsterDropDefinitions("被诅咒的僵尸0", 被诅咒的僵尸0);
    context.AddMonsterDropDefinitions("游荡恶鬼", 游荡恶鬼);
    context.AddMonsterDropDefinitions("游荡恶鬼0", 游荡恶鬼0);
    context.AddMonsterDropDefinitions("石化僵尸", 石化僵尸);
    context.AddMonsterDropDefinitions("石化僵尸0", 石化僵尸0);
    context.AddMonsterDropDefinitions("剧毒僵尸", 剧毒僵尸);
    context.AddMonsterDropDefinitions("剧毒僵尸0", 剧毒僵尸0);
    context.AddMonsterDropDefinitions("巨型尸王", 巨型尸王);
    context.AddMonsterDropDefinitions("幻影蜘蛛", 幻影蜘蛛);
    context.AddMonsterDropDefinitions("月魔蜘蛛", 月魔蜘蛛);
    context.AddMonsterDropDefinitions("天狼蜘蛛", 天狼蜘蛛);
    context.AddMonsterDropDefinitions("天狼蜘蛛0", 天狼蜘蛛0);
    context.AddMonsterDropDefinitions("天狼蜘蛛3", 天狼蜘蛛3);
    context.AddMonsterDropDefinitions("钢牙蜘蛛", 钢牙蜘蛛);
    context.AddMonsterDropDefinitions("钢牙蜘蛛0", 钢牙蜘蛛0);
    context.AddMonsterDropDefinitions("钢牙蜘蛛3", 钢牙蜘蛛3);
    context.AddMonsterDropDefinitions("黑锷蜘蛛", 黑锷蜘蛛);
    context.AddMonsterDropDefinitions("黑锷蜘蛛0", 黑锷蜘蛛0);
    context.AddMonsterDropDefinitions("黑锷蜘蛛3", 黑锷蜘蛛3);
    context.AddMonsterDropDefinitions("花吻蜘蛛", 花吻蜘蛛);
    context.AddMonsterDropDefinitions("花吻蜘蛛0", 花吻蜘蛛0);
    context.AddMonsterDropDefinitions("花吻蜘蛛3", 花吻蜘蛛3);
    context.AddMonsterDropDefinitions("血巨人", 血巨人);
    context.AddMonsterDropDefinitions("血巨人0", 血巨人0);
    context.AddMonsterDropDefinitions("血巨人3", 血巨人3);
    context.AddMonsterDropDefinitions("邪恶巨人", 邪恶巨人);
    context.AddMonsterDropDefinitions("邪恶巨人0", 邪恶巨人0);
    context.AddMonsterDropDefinitions("绿巨人", 绿巨人);
    context.AddMonsterDropDefinitions("红巨人", 红巨人);
    context.AddMonsterDropDefinitions("水晶蜘蛛", 水晶蜘蛛);
    context.AddMonsterDropDefinitions("赤月恶魔", 赤月恶魔);
    context.AddMonsterDropDefinitions("赤月恶魔1", 赤月恶魔1);
    context.AddMonsterDropDefinitions("邪恶巨人王", 邪恶巨人王);
    context.AddMonsterDropDefinitions("太阴月魔", 太阴月魔);
    context.AddMonsterDropDefinitions("蓝背蜘蛛", 蓝背蜘蛛);
    context.AddMonsterDropDefinitions("剧毒蓝背蛛", 剧毒蓝背蛛);
    context.AddMonsterDropDefinitions("太阴黑锷蛛", 太阴黑锷蛛);
    context.AddMonsterDropDefinitions("太阴花吻蛛", 太阴花吻蛛);
    context.AddMonsterDropDefinitions("太阴水晶蛛", 太阴水晶蛛);
    context.AddMonsterDropDefinitions("GreaterWeaver", GreaterWeaver);
    context.AddMonsterDropDefinitions("巨镰蜘蛛", 巨镰蜘蛛);
    context.AddMonsterDropDefinitions("金杖蜘蛛", 金杖蜘蛛);
    context.AddMonsterDropDefinitions("鸟人像", 鸟人像);
    context.AddMonsterDropDefinitions("石魔鬼尊", 石魔鬼尊);
    context.AddMonsterDropDefinitions("恶灵尸王", 恶灵尸王);
    context.AddMonsterDropDefinitions("恶灵尸王0", 恶灵尸王0);
    context.AddMonsterDropDefinitions("恶灵僵尸", 恶灵僵尸);
    context.AddMonsterDropDefinitions("恶灵僵尸0", 恶灵僵尸0);
    context.AddMonsterDropDefinitions("骷髅弓箭手", 骷髅弓箭手);
    context.AddMonsterDropDefinitions("骷髅弓箭手0", 骷髅弓箭手0);
    context.AddMonsterDropDefinitions("骷髅刀斧手", 骷髅刀斧手);
    context.AddMonsterDropDefinitions("骷髅刀斧手0", 骷髅刀斧手0);
    context.AddMonsterDropDefinitions("骷髅长枪兵", 骷髅长枪兵);
    context.AddMonsterDropDefinitions("骷髅长枪兵0", 骷髅长枪兵0);
    context.AddMonsterDropDefinitions("骷髅锤兵", 骷髅锤兵);
    context.AddMonsterDropDefinitions("骷髅锤兵0", 骷髅锤兵0);
    context.AddMonsterDropDefinitions("骸骨盘王", 骸骨盘王);
    context.AddMonsterDropDefinitions("远古恶灵尸王", 远古恶灵尸王);
    context.AddMonsterDropDefinitions("远古恶灵僵尸", 远古恶灵僵尸);
    context.AddMonsterDropDefinitions("远古骷髅弓箭手", 远古骷髅弓箭手);
    context.AddMonsterDropDefinitions("远古骷髅刀斧手", 远古骷髅刀斧手);
    context.AddMonsterDropDefinitions("远古骷髅长枪兵", 远古骷髅长枪兵);
    context.AddMonsterDropDefinitions("远古骷髅锤兵", 远古骷髅锤兵);
    context.AddMonsterDropDefinitions("远古骸骨盘王", 远古骸骨盘王);
    context.AddMonsterDropDefinitions("牛头魔", 牛头魔);
    context.AddMonsterDropDefinitions("牛头魔0", 牛头魔0);
    context.AddMonsterDropDefinitions("冰牛魔", 冰牛魔);
    context.AddMonsterDropDefinitions("冰牛魔0", 冰牛魔0);
    context.AddMonsterDropDefinitions("电光牛魔", 电光牛魔);
    context.AddMonsterDropDefinitions("电光牛魔0", 电光牛魔0);
    context.AddMonsterDropDefinitions("风之牛魔", 风之牛魔);
    context.AddMonsterDropDefinitions("风之牛魔0", 风之牛魔0);
    context.AddMonsterDropDefinitions("火焰牛魔", 火焰牛魔);
    context.AddMonsterDropDefinitions("火焰牛魔0", 火焰牛魔0);
    context.AddMonsterDropDefinitions("右护法", 右护法);
    context.AddMonsterDropDefinitions("右护法0", 右护法0);
    context.AddMonsterDropDefinitions("左护法", 左护法);
    context.AddMonsterDropDefinitions("左护法0", 左护法0);
    context.AddMonsterDropDefinitions("邪牛天王", 邪牛天王);
    context.AddMonsterDropDefinitions("魔龙刀斧手", 魔龙刀斧手);
    context.AddMonsterDropDefinitions("魔龙刀斧手0", 魔龙刀斧手0);
    context.AddMonsterDropDefinitions("魔龙刀兵", 魔龙刀兵);
    context.AddMonsterDropDefinitions("魔龙刀兵0", 魔龙刀兵0);
    context.AddMonsterDropDefinitions("魔龙射手", 魔龙射手);
    context.AddMonsterDropDefinitions("魔龙射手0", 魔龙射手0);
    context.AddMonsterDropDefinitions("魔龙巨蛾", 魔龙巨蛾);
    context.AddMonsterDropDefinitions("魔龙巨蛾0", 魔龙巨蛾0);
    context.AddMonsterDropDefinitions("魔龙战将", 魔龙战将);
    context.AddMonsterDropDefinitions("魔龙战将0", 魔龙战将0);
    context.AddMonsterDropDefinitions("魔龙力士", 魔龙力士);
    context.AddMonsterDropDefinitions("魔龙力士0", 魔龙力士0);
    context.AddMonsterDropDefinitions("阴之石碑", 阴之石碑);
    context.AddMonsterDropDefinitions("阳之石碑", 阳之石碑);
    context.AddMonsterDropDefinitions("凰天魔神", 凰天魔神);
    context.AddMonsterDropDefinitions("凰天魔魂", 凰天魔魂);
    context.AddMonsterDropDefinitions("ManectricHammer", ManectricHammer);
    context.AddMonsterDropDefinitions("ManectricClub", ManectricClub);
    context.AddMonsterDropDefinitions("ManectricClaw", ManectricClaw);
    context.AddMonsterDropDefinitions("ManectricSlave", ManectricSlave);
    context.AddMonsterDropDefinitions("Demon1", Demon1);
    context.AddMonsterDropDefinitions("Demon2", Demon2);
    context.AddMonsterDropDefinitions("ManectricBlest", ManectricBlest);
    context.AddMonsterDropDefinitions("ManectricKing", ManectricKing);
    context.AddMonsterDropDefinitions("梦魇", 梦魇);
    context.AddMonsterDropDefinitions("怨恶", 怨恶);
    context.AddMonsterDropDefinitions("HellSlasher", HellSlasher);
    context.AddMonsterDropDefinitions("HellPirate", HellPirate);
    context.AddMonsterDropDefinitions("HellCannibal", HellCannibal);
    context.AddMonsterDropDefinitions("HellBolt", HellBolt);
    context.AddMonsterDropDefinitions("WitchDoctor", WitchDoctor);
    context.AddMonsterDropDefinitions("CaveWitch", CaveWitch);
    context.AddMonsterDropDefinitions("HellKeeper", HellKeeper);
    context.AddMonsterDropDefinitions("白象", 白象);
    context.AddMonsterDropDefinitions("TucsonEgg", TucsonEgg);
    context.AddMonsterDropDefinitions("YoungTucson", YoungTucson);
    context.AddMonsterDropDefinitions("VisceralWorm2", VisceralWorm2);
    context.AddMonsterDropDefinitions("SandSnail", SandSnail);
    context.AddMonsterDropDefinitions("CannibalTentacles", CannibalTentacles);
    context.AddMonsterDropDefinitions("Tucson", Tucson);
    context.AddMonsterDropDefinitions("TucsonFighter", TucsonFighter);
    context.AddMonsterDropDefinitions("TucsonMage", TucsonMage);
    context.AddMonsterDropDefinitions("TucsonWarrior", TucsonWarrior);
    context.AddMonsterDropDefinitions("GeneralTucson", GeneralTucson);
    context.AddMonsterDropDefinitions("HellKnight1", HellKnight1);
    context.AddMonsterDropDefinitions("HellKnight2", HellKnight2);
    context.AddMonsterDropDefinitions("HellKnight3", HellKnight3);
    context.AddMonsterDropDefinitions("HellBomb1", HellBomb1);
    context.AddMonsterDropDefinitions("HellBomb2", HellBomb2);
    context.AddMonsterDropDefinitions("HornedArcher", HornedArcher);
    context.AddMonsterDropDefinitions("HornedCommander", HornedCommander);
    context.AddMonsterDropDefinitions("HornedMage", HornedMage);
    context.AddMonsterDropDefinitions("HornedWarrior", HornedWarrior);
    context.AddMonsterDropDefinitions("BoulderSpirit", BoulderSpirit);
    context.AddMonsterDropDefinitions("Ancient_ZumaTaurus", Ancient_ZumaTaurus);
    context.AddMonsterDropDefinitions("Frozen_ZumaStatue", Frozen_ZumaStatue);
    context.AddMonsterDropDefinitions("Frozen_ZumaGuardian", Frozen_ZumaGuardian);
    context.AddMonsterDropDefinitions("Frozen_RedZuma", Frozen_RedZuma);
}
